App\Entity\Location:
  properties:
    latitude:
      - Range:
          min: -90
          max: 90
          notInRangeMessage: The latitude must be between {{ min }} and {{ max }} degrees
          groups: [new, edit]
    longitude:
      - Range:
          min: -180
          max: 180
          notInRangeMessage: The latitude must be between {{ min }} and {{ max }} degrees
          groups: [new, edit]

App\Entity\Forecast:
  properties:
    pressure:
      - GreaterThanOrEqual:
          value: 900
          groups: [new, edit]
    humidity:
      - Range:
          min: 0
          max: 100
          groups: [new, edit]
    windSpeed:
      - PositiveOrZero:
          groups: [new, edit]
    windDeg:
      - PositiveOrZero:
          groups: [new, edit]
      - LessThan:
          value: 360
          groups: [new, edit]
    cloudiness:
      - Range:
          min: 0
          max: 100
          groups: [new, edit]
    # icon:
    #   - Choice:
    #       choices: [ sun, cloud ]
    #       groups: [new, edit]